# Generated by Django 4.0.4 on 2022-05-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag_name',
            field=models.ManyToManyField(blank=True, to='blog.tag'),
        ),
    ]
