# Generated by Django 4.0.4 on 2022-05-27 11:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_slug_alter_post_tag_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag_name',
            new_name='tags',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author_name',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='email_adress',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name=django.core.validators.MinLengthValidator(20)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='caption',
            field=models.CharField(max_length=20),
        ),
    ]
