# Generated by Django 4.0.4 on 2022-05-27 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_tag_name_post_tags_remove_post_author_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
    ]
